/**
 * CARS (Childhood Autism Rating Scale) 孤独症评定量表评估目录
 * 从 CARS_专业评估表.xlsx 自动提取
 * 121 项技能,跨 14 个领域(9 个功能领域 + 4 个病理学领域)
 *
 * 注意:这是静态目录,数据库启动时种入 cars_items 表;运行时只查表,不读这里。
 * 修改目录后需要(1) 改这里 (2) 改 lib/db.ts 的 seed 逻辑或手动 UPDATE 表。
 */

export type CarsDomain = {
  code: string;
  label: string;
  label_en: string;
  item_count: number;
  is_pathology: boolean;
};

export type CarsItem = {
  domain_code: string;
  item_code: string;
  name: string;
  goal: string;
  materials?: string | null;
  method?: string | null;
  is_observation?: boolean;
  order_in_domain: number;
};

export const CARS_DOMAINS: CarsDomain[] = [
  {
    code: "perception_visual",
    label: "知觉(视觉)",
    label_en: "Perception (Visual)",
    item_count: 15,
    is_pathology: false,
  },
  {
    code: "perception_auditory",
    label: "知觉(听觉)",
    label_en: "Perception (Auditory)",
    item_count: 3,
    is_pathology: false,
  },
  {
    code: "imitation_motor",
    label: "模仿(动作)",
    label_en: "Imitation (Motor)",
    item_count: 7,
    is_pathology: false,
  },
  {
    code: "imitation_verbal",
    label: "模仿(口语)",
    label_en: "Imitation (Verbal)",
    item_count: 5,
    is_pathology: false,
  },
  {
    code: "fine_motor",
    label: "精细动作",
    label_en: "Fine Motor",
    item_count: 11,
    is_pathology: false,
  },
  {
    code: "eye_hand",
    label: "手眼协调",
    label_en: "Eye-Hand Coordination",
    item_count: 15,
    is_pathology: false,
  },
  {
    code: "gross_motor",
    label: "粗大动作",
    label_en: "Gross Motor",
    item_count: 11,
    is_pathology: false,
  },
  {
    code: "verbal_cognition",
    label: "口语认知",
    label_en: "Verbal Cognition",
    item_count: 18,
    is_pathology: false,
  },
  {
    code: "cognition_performance",
    label: "认知表现",
    label_en: "Cognitive Performance",
    item_count: 20,
    is_pathology: false,
  },
  {
    code: "sensation",
    label: "感觉",
    label_en: "Sensation",
    item_count: 8,
    is_pathology: true,
  },
  {
    code: "emotion",
    label: "感情",
    label_en: "Emotion",
    item_count: 3,
    is_pathology: true,
  },
  {
    code: "social_interaction",
    label: "人际关系、合作行为及对人的兴趣",
    label_en: "Social Interaction",
    item_count: 3,
    is_pathology: true,
  },
  {
    code: "play_interest",
    label: "游戏及对物的兴趣",
    label_en: "Play and Interest in Objects",
    item_count: 2,
    is_pathology: true,
  },
];

export const CARS_ITEMS: CarsItem[] = [
  {
    domain_code: "perception_visual",
    item_code: "1C",
    name: "目光追随泡泡的移动",
    goal: "观察孩子是否能用目光追随泡泡移动",
    materials: "同1A",
    method: `在实施项目1B(吹泡泡)的过程中观察孩子。在示范过程及孩子试图完成任务的时候，注意他是否用目光追随泡泡的移动。`,
    is_observation: true,
    order_in_domain: 1,
  },
  {
    domain_code: "perception_visual",
    item_code: "8A",
    name: "完成三块式几何图形的拼图",
    goal: "测试孩子是否能完成几何图形拼图",
    materials: "三块式几何图形(圆形、正方形、三角形)拼图板",
    method: `把三块式几何图形拼图板放在孩子面前的桌子上。三角形的底边要对着孩子。把圆形、正方形、三角形的拼块取出，放在模板和孩子中间。要确保每一拼块都不要正对着模板上的图形位置。然后指着模板向孩子说明去把图形拼块放进去。`,
    order_in_domain: 2,
  },
  {
    domain_code: "perception_visual",
    item_code: "9",
    name: "完成四块式图形拼图",
    goal: "测试孩子是否能完成四块式图形拼图",
    materials: "四块式(雨伞、小鸡、蝴蝶、梨)拼图板",
    method: `把拼图板放在桌上，要面对着孩子放。递给他一个拼图块，并指着模板向他说明把拼块放进去。一旦把这块放进去了，再递给他另一块。对其他几块要重复同样的实施步骤。`,
    order_in_domain: 3,
  },
  {
    domain_code: "perception_visual",
    item_code: "11A",
    name: "完成三块式连指手套图形拼图",
    goal: "测试孩子是否能完成连指手套拼图",
    materials: "三块式连指手套图形拼图板",
    method: `将连指手套图形拼图形放在孩子面前的桌子上，把3个拼块放在孩子和拼图板之间，要确保每一拼块不与其位置对应。然后指着拼图板向孩子说明把拼块放进去。`,
    order_in_domain: 4,
  },
  {
    domain_code: "perception_visual",
    item_code: "14A",
    name: "根据颜色将杯碟配对",
    goal: "测试孩子是否能根据颜色将杯碟配对",
    materials: "五套不同颜色(黄、红、蓝、绿和白色)的杯子和碟子",
    method: `任意选择3套杯子、碟子，把碟子放在孩子面前的桌子上，递给孩子一只杯子，并指着这些碟子向孩子说明去将这只杯子放在相同颜色的碟子上。`,
    order_in_domain: 5,
  },
  {
    domain_code: "perception_visual",
    item_code: "30",
    name: "对手势作出反应",
    goal: "测试孩子是否能对手势作出反应",
    method: `仅在没有观察到孩子具有对手势作出反应的能力时，才实施这个项目。用手势而不附加任何口头提示。`,
    order_in_domain: 6,
  },
  {
    domain_code: "perception_visual",
    item_code: "32",
    name: "照样画垂直线",
    goal: "测试孩子是否能照样画垂直线",
    materials: "同31",
    method: `打开小本子，翻到适当的一页，放到孩子面前。指着样本向孩子说明照着去画。允许孩子试三次去照样画。`,
    order_in_domain: 7,
  },
  {
    domain_code: "perception_visual",
    item_code: "33",
    name: "照样画圆",
    goal: "测试孩子是否能照样画圆",
    materials: "同31",
    method: `同32`,
    order_in_domain: 8,
  },
  {
    domain_code: "perception_visual",
    item_code: "34",
    name: "照样画正方形",
    goal: "测试孩子是否能照样画正方形",
    materials: "同31",
    method: `同32`,
    order_in_domain: 9,
  },
  {
    domain_code: "perception_visual",
    item_code: "35",
    name: "照样画三角形",
    goal: "测试孩子是否能照样画三角形",
    materials: "同31",
    method: `同32`,
    order_in_domain: 10,
  },
  {
    domain_code: "perception_visual",
    item_code: "36",
    name: "画菱形",
    goal: "测试孩子是否能画菱形",
    materials: "同31",
    method: `同32`,
    order_in_domain: 11,
  },
  {
    domain_code: "perception_visual",
    item_code: "37",
    name: "在小兔子图片线条范围内着色",
    goal: "测试孩子是否能在小兔子图片线条范围内着色",
    materials: "同31",
    method: `打开小册子翻到小兔子的图片那一页，向孩子说明去给兔子的尾巴、耳朵或脚着色。`,
    order_in_domain: 12,
  },
  {
    domain_code: "perception_visual",
    item_code: "49A",
    name: "堆放8块积木",
    goal: "测试孩子是否能堆放8块积木",
    materials: "12块小积木，放在一个盒子里",
    method: `把积木放在孩子面前的桌子上，向他示范如何把积木一块压一块地堆起来。然后把积木重新放回到桌子上，向孩子说明去照样做。`,
    is_observation: true,
    order_in_domain: 13,
  },
  {
    domain_code: "perception_visual",
    item_code: "58",
    name: "找到藏在杯子下的糖果",
    goal: "测试孩子是否能找到藏在杯子下的糖果",
    materials: "3只杯子和一些糖果",
    method: `在桌子上把3只杯子摆成一排，并引起孩子的注意。把一块糖果放在中间杯子下，缓慢地把中间的杯子与你右手的杯子变换位置，向孩子说明去找到糖果。`,
    is_observation: true,
    order_in_domain: 14,
  },
  {
    domain_code: "perception_visual",
    item_code: "62A",
    name: "对图册显示兴趣",
    goal: "测试孩子是否对图册显示兴趣",
    materials: "语言读本",
    method: `把语言读本放在孩子面前的桌子上。一段时间之后，如果他还没有去打开，就鼓励他去打开。`,
    order_in_domain: 15,
  },
  {
    domain_code: "perception_auditory",
    item_code: "16",
    name: "听见并寻找响板声音的方位",
    goal: "测试孩子听见响板声后的反应及方向辨认",
    materials: "响板",
    method: `当孩子从事另一项任务时把响板放在孩子看不到的地方然后响亮地发出啪啪声，注意孩子的反应。`,
    order_in_domain: 1,
  },
  {
    domain_code: "perception_auditory",
    item_code: "29",
    name: "听见并寻找哨声方位",
    goal: "测试孩子听见哨声后的反应及方向辨认",
    materials: "一只哨子",
    method: `当孩子从事另外一项活动时，把哨子藏在手里，然后大声地吹，并注意孩子的反应。`,
    order_in_domain: 2,
  },
  {
    domain_code: "perception_auditory",
    item_code: "60",
    name: "听见并寻找手摇铃声音的方位",
    goal: "测试孩子听见手摇铃声后的反应及方向辨认",
    materials: "一个手摇铃",
    method: `当孩子从事另一项活动时，藏起手摇铃。然后用力摇动，并注意孩子的反应。`,
    order_in_domain: 3,
  },
  {
    domain_code: "imitation_motor",
    item_code: "1A",
    name: "拧开泡泡瓶盖",
    goal: "测试孩子是否能独立拧开泡泡瓶盖",
    materials: "一瓶肥皂泡液，吹泡泡的杆",
    method: `把泡泡瓶放在桌上说：'这是泡泡瓶'。把瓶子递给孩子，向他简要说明去拧开盖子。如果他不能打开，就做一下示范，然后再次让孩子拧开盖子。`,
    order_in_domain: 1,
  },
  {
    domain_code: "imitation_motor",
    item_code: "1B",
    name: "吹泡泡",
    goal: "测试孩子是否能吹出泡泡",
    materials: "同1A",
    method: `给孩子示范如何吹泡泡，向他说明要照着去做，然后把吹杆递给孩子。`,
    order_in_domain: 2,
  },
  {
    domain_code: "imitation_motor",
    item_code: "3A",
    name: "操作万花筒",
    goal: "测试孩子是否能模仿操作万花筒",
    materials: "一只万花筒",
    method: `给孩子做示范如何看万花筒以及怎样转动底部。向孩子说明照样去做，然后将万花筒给他。`,
    order_in_domain: 3,
  },
  {
    domain_code: "imitation_motor",
    item_code: "4",
    name: "按手铃两次",
    goal: "测试孩子是否能模仿按手铃两次",
    materials: "一只手铃",
    method: `把铃放在孩子面前的桌子上，引起他的注意('注意我做了什么')。快速连续按铃两次，向孩子说明照样去做。`,
    order_in_domain: 4,
  },
  {
    domain_code: "imitation_motor",
    item_code: "5A",
    name: "把胶泥搓成长条",
    goal: "测试孩子是否能模仿把胶泥搓成长条",
    materials: "胶泥",
    method: `把一块胶泥分成两块，给孩子一块。示范如何把胶泥在桌子上搓成长条，向孩子说明照样去做。`,
    order_in_domain: 5,
  },
  {
    domain_code: "imitation_motor",
    item_code: "6A",
    name: "将手偶猫套在手上并操纵",
    goal: "测试孩子是否能将手偶套在手上并操纵",
    materials: "一只手偶猫",
    method: `拿手偶猫给孩子看，告诉他'这是猫'。把手偶猫套在你的手上说：'我是猫咪。喵，我要亲亲你'，然后用手偶象征性地亲一亲孩子。把手偶猫递给他说：'你来当猫咪。'`,
    order_in_domain: 6,
  },
  {
    domain_code: "imitation_motor",
    item_code: "28",
    name: "模仿粗大动作",
    goal: "测试孩子是否能模仿粗大动作",
    method: `引起孩子的注意，然后做下列动作：a、举起一只胳膊 b、摸一下鼻子 c、举起一只胳膊同时用另一只手摸鼻子。`,
    is_observation: true,
    order_in_domain: 7,
  },
  {
    domain_code: "imitation_verbal",
    item_code: "6B",
    name: "模仿动物(手偶)的声音",
    goal: "测试孩子是否能模仿手偶发出的动物声音",
    materials: "一只手偶猫和一只手偶狗",
    method: `在实施项目6A的过程中，引导孩子模仿声音。发出'喵喵'、'汪汪'等声音并向孩子说明也这样做。`,
    order_in_domain: 1,
  },
  {
    domain_code: "imitation_verbal",
    item_code: "15A",
    name: "复述两位数及三位数",
    goal: "测试孩子是否能复述两位数及三位数",
    method: `引起孩子注意。对他说：'我要念一些数字，你仔细听着。我念完之后你来说。'让孩子依顺序重复两位数及三位数，每组都试读两次。`,
    order_in_domain: 2,
  },
  {
    domain_code: "imitation_verbal",
    item_code: "15B",
    name: "重复四位数及五位数",
    goal: "测试孩子是否能重复四位数及五位数",
    method: `实施步骤、功能领域及评分标准同15A。`,
    order_in_domain: 3,
  },
  {
    domain_code: "imitation_verbal",
    item_code: "63",
    name: "口头模仿\'M-M\'、\'BA-BA\'、\'PA-TA\'及\'LA-LA\'",
    goal: "测试孩子是否能口头模仿发音",
    method: `引起孩子注意，向他说明去重复你所说的内容。然后说'Mmm'，并向他说明去复述。对ba-ba，pa-ta，la-la这些声音依照同样的步骤实施。`,
    order_in_domain: 4,
  },
  {
    domain_code: "imitation_verbal",
    item_code: "64",
    name: "模仿单词\'向上\'、\'做饭\'、\'宝宝\'",
    goal: "测试孩子是否能模仿单词",
    method: `引起孩子注意，要孩子去说'向上'，'做饭'、'宝宝'这些单词。`,
    order_in_domain: 5,
  },
  {
    domain_code: "fine_motor",
    item_code: "1A",
    name: "拧开泡泡瓶盖",
    goal: "测试孩子是否能独立拧开泡泡瓶盖",
    materials: "一瓶肥皂泡液，吹泡泡的杆",
    method: `把泡泡瓶放在桌上说：'这是泡泡瓶'。把瓶子递给孩子，向他简要说明去拧开盖子。如果他不能打开，就做一下示范，然后再次让孩子拧开盖子。`,
    order_in_domain: 1,
  },
  {
    domain_code: "fine_motor",
    item_code: "1B",
    name: "吹泡泡",
    goal: "测试孩子是否能吹出泡泡",
    materials: "同1A",
    method: `给孩子示范如何吹泡泡，向他说明要照着去做，然后把吹杆递给孩子。`,
    order_in_domain: 2,
  },
  {
    domain_code: "fine_motor",
    item_code: "5B",
    name: "用胶泥捏成碗状",
    goal: "测试孩子是否能用胶泥捏成碗状",
    materials: "同5A",
    method: `示范给孩子看如何把胶泥捏成碗状，然后向孩子说明照着去做。`,
    order_in_domain: 3,
  },
  {
    domain_code: "fine_motor",
    item_code: "24",
    name: "大拇指依次触碰其他手指",
    goal: "测试孩子是否能用大拇指依次触碰其他手指",
    method: `站在孩子旁边与孩子脸朝同一方向。引起他的注意，在他面前举起一只手，手掌对着他，伸开手指。示范给孩子看如何用同一只手的大拇指依次触碰每个手指的指尖。`,
    order_in_domain: 4,
  },
  {
    domain_code: "fine_motor",
    item_code: "39",
    name: "抄写7个汉字",
    goal: "测试孩子是否能抄写7个汉字",
    materials: "同38A",
    method: `打开小册子，翻到适当的一页，放在孩子面前。指着第一个字说明让他照着写。`,
    order_in_domain: 5,
  },
  {
    domain_code: "fine_motor",
    item_code: "40",
    name: "画一个人",
    goal: "测试孩子是否能画出一个人",
    materials: "同38A",
    method: `打开小册子，翻到空白页，放在孩子面前。要他去'画一个人'。`,
    order_in_domain: 6,
  },
  {
    domain_code: "fine_motor",
    item_code: "43",
    name: "在小袋内通过触摸辨认5种物品",
    goal: "测试孩子是否能通过触摸辨认袋内5种物品",
    materials: "一只小口袋，内有一支铅笔，一块积木，一支蜡笔，一只球以及一枚硬币",
    method: `把装有物品的袋子放在孩子面前的桌子上。不让孩子往袋子里看，要他把手伸进袋子，告诉他把你所要求的每一件物品拿出来。`,
    order_in_domain: 7,
  },
  {
    domain_code: "fine_motor",
    item_code: "45",
    name: "用剪子剪纸",
    goal: "测试孩子是否能用剪刀剪纸",
    materials: "一张纸、一把剪子",
    method: `示范给孩子看如何用剪刀剪纸，然后向他说明照着去做。把纸和剪刀递给孩子。`,
    is_observation: true,
    order_in_domain: 8,
  },
  {
    domain_code: "fine_motor",
    item_code: "54B",
    name: "穿珠子",
    goal: "测试孩子是否能穿珠子",
    materials: "同54A",
    method: `把两颗珠子放在孩子面前的桌子上。向他说明去穿珠子。`,
    order_in_domain: 9,
  },
  {
    domain_code: "fine_motor",
    item_code: "55",
    name: "两手并用",
    goal: "观察孩子是否能两手并用协调操作",
    method: `在孩子穿珠子、剪纸、或上颜色的过程中，或在正常情况下需用两只手来完成的任何其他项任务的过程中，观察孩子。`,
    is_observation: true,
    order_in_domain: 10,
  },
  {
    domain_code: "fine_motor",
    item_code: "57",
    name: "用(大拇指及食指)握成钳形来夹取一块糖果",
    goal: "测试孩子是否能用钳形手势夹取糖果",
    materials: "一块糖果",
    method: `把一块糖果放在你的手掌里，稍稍握紧紧这只手，把糖果给孩子，注意他是如何拿起糖果的。`,
    order_in_domain: 11,
  },
  {
    domain_code: "eye_hand",
    item_code: "8A",
    name: "完成三块式几何图形的拼图",
    goal: "测试孩子是否能完成几何图形拼图",
    materials: "三块式几何图形(圆形、正方形、三角形)拼图板",
    method: `把三块式几何图形拼图板放在孩子面前的桌子上。三角形的底边要对着孩子。把圆形、正方形、三角形的拼块取出，放在模板和孩子中间。要确保每一拼块都不要正对着模板上的图形位置。然后指着模板向孩子说明去把图形拼块放进去。`,
    order_in_domain: 1,
  },
  {
    domain_code: "eye_hand",
    item_code: "11A",
    name: "完成三块式连指手套图形拼图",
    goal: "测试孩子是否能完成连指手套拼图",
    materials: "三块式连指手套图形拼图板",
    method: `将连指手套图形拼图形放在孩子面前的桌子上，把3个拼块放在孩子和拼图板之间，要确保每一拼块不与其位置对应。然后指着拼图板向孩子说明把拼块放进去。`,
    order_in_domain: 2,
  },
  {
    domain_code: "eye_hand",
    item_code: "12",
    name: "完成四块式小猫图形联锁式拼图",
    goal: "测试孩子是否能完成小猫联锁式拼图",
    materials: "四块式小猫图形联锁式拼图板",
    method: `把拼图块放在桌子上向孩子说明要把拼图块拼到一起('把它们拼起来')。如果一段时间之后孩子仍难于理解或完成这项任务，则用四个拼块示范给他看。`,
    order_in_domain: 3,
  },
  {
    domain_code: "eye_hand",
    item_code: "31",
    name: "自发地涂鸦",
    goal: "测试孩子是否能自发地涂鸦",
    materials: "孩子的书写本和一支蜡笔",
    method: `向孩子说明坐回到桌子旁的座位上，打开书写本，翻到第一空页，把书写本放在孩子面前，然后给一支蜡笔，向他说明去涂写。`,
    order_in_domain: 4,
  },
  {
    domain_code: "eye_hand",
    item_code: "32",
    name: "照样画垂直线",
    goal: "测试孩子是否能照样画垂直线",
    materials: "同31",
    method: `打开小本子，翻到适当的一页，放到孩子面前。指着样本向孩子说明照着去画。允许孩子试三次去照样画。`,
    order_in_domain: 5,
  },
  {
    domain_code: "eye_hand",
    item_code: "33",
    name: "照样画圆",
    goal: "测试孩子是否能照样画圆",
    materials: "同31",
    method: `同32`,
    order_in_domain: 6,
  },
  {
    domain_code: "eye_hand",
    item_code: "34",
    name: "照样画正方形",
    goal: "测试孩子是否能照样画正方形",
    materials: "同31",
    method: `同32`,
    order_in_domain: 7,
  },
  {
    domain_code: "eye_hand",
    item_code: "35",
    name: "照样画三角形",
    goal: "测试孩子是否能照样画三角形",
    materials: "同31",
    method: `同32`,
    order_in_domain: 8,
  },
  {
    domain_code: "eye_hand",
    item_code: "36",
    name: "画菱形",
    goal: "测试孩子是否能画菱形",
    materials: "同31",
    method: `同32`,
    order_in_domain: 9,
  },
  {
    domain_code: "eye_hand",
    item_code: "37",
    name: "在小兔子图片线条范围内着色",
    goal: "测试孩子是否能在小兔子图片线条范围内着色",
    materials: "同31",
    method: `打开小册子翻到小兔子的图片那一页，向孩子说明去给兔子的尾巴、耳朵或脚着色。`,
    order_in_domain: 10,
  },
  {
    domain_code: "eye_hand",
    item_code: "38A",
    name: "匹配9个汉字",
    goal: "测试孩子是否能匹配9个汉字",
    materials: "汉字表以及9张汉字卡(大、小、人、头、手、日、月、土、木)",
    method: `打开书写本翻到汉字表这一页，把它放到孩子面前。递给他汉字卡'大'并指着汉字表，向他说明拿手中的汉字卡与汉字表上对应的汉字匹配。`,
    order_in_domain: 11,
  },
  {
    domain_code: "eye_hand",
    item_code: "39",
    name: "抄写7个汉字",
    goal: "测试孩子是否能抄写7个汉字",
    materials: "同38A",
    method: `打开小册子，翻到适当的一页，放在孩子面前。指着第一个字说明让他照着写。`,
    order_in_domain: 12,
  },
  {
    domain_code: "eye_hand",
    item_code: "44",
    name: "用毡块贴出男孩图象",
    goal: "测试孩子是否能用毡块贴出男孩图象",
    materials: "一块毡板，九块毡片(脸，带胳膊的躯体，两条腿，头发，眼睛，鼻子和嘴)",
    method: `把毡板和毡块放在孩子面前的桌子上。用其中一块作示范，告诉孩子怎样往毡板上贴毡片。`,
    order_in_domain: 13,
  },
  {
    domain_code: "eye_hand",
    item_code: "49A",
    name: "堆放8块积木",
    goal: "测试孩子是否能堆放8块积木",
    materials: "12块小积木，放在一个盒子里",
    method: `把积木放在孩子面前的桌子上，向他示范如何把积木一块压一块地堆起来。然后把积木重新放回到桌子上，向孩子说明去照样做。`,
    is_observation: true,
    order_in_domain: 14,
  },
  {
    domain_code: "eye_hand",
    item_code: "49B",
    name: "把积木放入盒子中",
    goal: "测试孩子是否能将积木放入盒子中",
    materials: "同49A",
    method: `把一只小盒子放在桌子上积木块的旁边，向孩子说明把积木放到盒子中去。`,
    order_in_domain: 15,
  },
  {
    domain_code: "gross_motor",
    item_code: "17A",
    name: "接球",
    goal: "测试孩子是否能接住抛来的球",
    materials: "一只大橡皮球",
    method: `站起来离开桌子，向孩子说明要他也这样做。拿球给他看，并向他说明你来抛球。然后站在孩子附近，轻轻地把球抛给他。`,
    order_in_domain: 1,
  },
  {
    domain_code: "gross_motor",
    item_code: "17B",
    name: "抛球",
    goal: "测试孩子是否能将球抛给测试者",
    materials: "同17A",
    method: `在实施项目17A(接球)过程中注意孩子如何把球抛给你。`,
    is_observation: true,
    order_in_domain: 2,
  },
  {
    domain_code: "gross_motor",
    item_code: "17C",
    name: "踢球",
    goal: "测试孩子是否能踢球",
    materials: "同17A",
    method: `示范给孩子看如何踢球。向他说明也这样做。然后把球递给他，让孩子试踢三次。`,
    order_in_domain: 3,
  },
  {
    domain_code: "gross_motor",
    item_code: "19",
    name: "单独行走",
    goal: "测试孩子是否能单独行走",
    method: `让孩子站起来，然后向他说明去走路。要确保他没有接近任何可能用来支持他行走的东西。`,
    order_in_domain: 4,
  },
  {
    domain_code: "gross_motor",
    item_code: "20",
    name: "上楼梯(每个台阶一只脚)",
    goal: "测试孩子是否能上楼梯（每台阶一只脚）",
    materials: "阶梯(最好无扶手)",
    method: `和孩子一起站在阶梯前，示范如何上台阶，然后向孩子说明也这样做。`,
    order_in_domain: 5,
  },
  {
    domain_code: "gross_motor",
    item_code: "21",
    name: "拍手",
    goal: "测试孩子是否能模仿拍手",
    method: `示范给孩子看如何拍手。拍上几次，然后向孩子说明也这样做。`,
    order_in_domain: 6,
  },
  {
    domain_code: "gross_motor",
    item_code: "22A",
    name: "单脚站立",
    goal: "测试孩子是否能单脚站立",
    method: `示范给孩子看如何单脚站立。向他说明也这样做。`,
    is_observation: true,
    order_in_domain: 7,
  },
  {
    domain_code: "gross_motor",
    item_code: "22B",
    name: "双脚原地上下跳动",
    goal: "测试孩子是否能双脚原地上下跳动",
    method: `给孩子示范如何同时使用双脚在原地上下跳动。向他说明也这样做。`,
    order_in_domain: 8,
  },
  {
    domain_code: "gross_motor",
    item_code: "23",
    name: "学步车推车走",
    goal: "测试孩子是否能推学步车行走",
    materials: "装有轮子的学步车",
    method: `向孩子说明去坐在学步车上。鼓励他推着自己绕房间走动。`,
    order_in_domain: 9,
  },
  {
    domain_code: "gross_motor",
    item_code: "54C",
    name: "象钟摆一样摆动穿在绳上的两颗珠子",
    goal: "测试孩子是否能象钟摆一样摆动珠子",
    materials: "同54A",
    method: `把两颗珠子穿孔绳子上。站起来并向孩子说明和你一样站起来。然后举起绳子示范如何象钟摆那样往复摆动珠子。`,
    order_in_domain: 10,
  },
  {
    domain_code: "gross_motor",
    item_code: "56",
    name: "把物品从一只手转移到另一只手",
    goal: "观察孩子是否能将物品从一只手转移到另一只手",
    method: `在拼图或穿珠子等项目的过程中观察孩子。注意孩子是否能自由地把物品从一只手转到另一只手上。`,
    is_observation: true,
    order_in_domain: 11,
  },
  {
    domain_code: "verbal_cognition",
    item_code: "8B",
    name: "表达性辨认三种几何形状",
    goal: "测试孩子是否能表达性辨认三种几何形状",
    materials: "同8A",
    method: `将三个几何图形拼块放在桌子上，指着圆形问孩子：'这是什么?'对正方形、三角形要重复同样的实施步骤。`,
    order_in_domain: 1,
  },
  {
    domain_code: "verbal_cognition",
    item_code: "11B",
    name: "大小概念(表达性辨认大小)",
    goal: "测试孩子是否能表达性辨认大小概念",
    materials: "同11A",
    method: `把连指手套拼图板上最大和最小的两个拼块放在桌子上。指导小块放在孩子的左边，大块放在右边。然后指着这两个拼块对孩子说'看看这两块东西，它们是不一样的，有什么不一样？'`,
    order_in_domain: 2,
  },
  {
    domain_code: "verbal_cognition",
    item_code: "14B",
    name: "表达性辨认5种颜色",
    goal: "测试孩子是否能表达性辨认5种颜色",
    materials: "同14A",
    method: `把5个碟子全部放在桌子上。指着或拿起一个碟子问'这是什么颜色的?'对其余的碟子重复同样的实施步骤。`,
    order_in_domain: 3,
  },
  {
    domain_code: "verbal_cognition",
    item_code: "15A",
    name: "复述两位数及三位数",
    goal: "测试孩子是否能复述两位数及三位数",
    method: `引起孩子注意。对他说：'我要念一些数字，你仔细听着。我念完之后你来说。'让孩子依顺序重复两位数及三位数，每组都试读两次。`,
    order_in_domain: 4,
  },
  {
    domain_code: "verbal_cognition",
    item_code: "15B",
    name: "重复四位数及五位数",
    goal: "测试孩子是否能重复四位数及五位数",
    method: `实施步骤、功能领域及评分标准同15A。`,
    order_in_domain: 5,
  },
  {
    domain_code: "verbal_cognition",
    item_code: "38B",
    name: "表达性辨认9个汉字",
    goal: "测试孩子是否能表达性辨认9个汉字",
    materials: "同38A",
    method: `把9张汉字卡放在桌子上，任意指着一个汉字，问孩子'这是什么字?'。`,
    order_in_domain: 6,
  },
  {
    domain_code: "verbal_cognition",
    item_code: "49C",
    name: "数出2到7块积木",
    goal: "测试孩子是否能数出2到7块积木",
    materials: "同49A，但只使用颜色相同的积木",
    method: `把两块积木放在孩子面前的桌子上，向他说明数的时候要指着每一块积木。`,
    order_in_domain: 7,
  },
  {
    domain_code: "verbal_cognition",
    item_code: "51",
    name: "唱数1到10",
    goal: "测试孩子是否能唱数1到10",
    method: `让孩子大声数。如果孩子似乎难于理解这项任务，就帮助他，说'1，下一个是几?'`,
    order_in_domain: 8,
  },
  {
    domain_code: "verbal_cognition",
    item_code: "52",
    name: "表达性辨认数1-10",
    goal: "测试孩子是否能表达性辨认数1-10",
    materials: "10张卡片上面写有1-10的10个数字",
    method: `随意选择一张数卡。拿起卡片靠近孩子，问他'这是几?'`,
    order_in_domain: 9,
  },
  {
    domain_code: "verbal_cognition",
    item_code: "53A",
    name: "心算加法和减法题",
    goal: "测试孩子心算加法和减法题",
    method: `把3道题读给他听：a)假如你有一只球，我再给你两只球，你一共有几只球? b)假如你有两个硬币，我再给你4个硬币，你一共有多少硬币? c)假如你有5个娃娃，送掉两个，你还剩几个?`,
    order_in_domain: 10,
  },
  {
    domain_code: "verbal_cognition",
    item_code: "53B",
    name: "心算出加法和减法题",
    goal: "测试孩子心算加法和减法题（变式）",
    method: `此项实施步骤同53A。a)小刚有5只球，送掉2只，他还剩下几只? b)佳佳有2个硬币，他妈妈又给他4个硬币，他一共有多少? c)南南有3个娃娃，她爸爸又给了她1个，她一共有多少个?`,
    order_in_domain: 11,
  },
  {
    domain_code: "verbal_cognition",
    item_code: "62C",
    name: "表达性辨认语言读本上的图片",
    goal: "测试孩子是否能表达性辨认语言读本图片",
    materials: "同62A",
    method: `打开语言读本。指着奶牛问孩子'这是什么?'。`,
    order_in_domain: 12,
  },
  {
    domain_code: "verbal_cognition",
    item_code: "65",
    name: "模仿短语\'宝宝往上看\'、\'我要纸\'及\'他不哭\'",
    goal: "测试孩子是否能模仿短语",
    method: `引起孩子的注意，要孩子复述这些短语。词语应当以每秒两个字的速率说出。`,
    order_in_domain: 13,
  },
  {
    domain_code: "verbal_cognition",
    item_code: "66",
    name: "模仿简单句",
    goal: "测试孩子是否能模仿简单句",
    method: `要孩子复述下列句子：'宝宝敲打一只红色的球。''我看见一架飞机在高空中飞。''康康买了一只娃娃和一辆车。'`,
    order_in_domain: 14,
  },
  {
    domain_code: "verbal_cognition",
    item_code: "67",
    name: "模仿复合句",
    goal: "测试孩子是否能模仿复合句",
    method: `要孩子复述下列句子：1)虽然我的狗汪汪叫，但猫却没有跑。2)在吃饭之前，我总是先洗手。3)要是你坐好了，就给你一本书。`,
    order_in_domain: 15,
  },
  {
    domain_code: "verbal_cognition",
    item_code: "69A",
    name: "读出简短的词",
    goal: "测试孩子是否能读出简短的词",
    materials: "语言读本",
    method: `打开语言读本，翻到故事这一页，要孩子去朗读。`,
    order_in_domain: 16,
  },
  {
    domain_code: "verbal_cognition",
    item_code: "69B",
    name: "读出故事中的一个短句",
    goal: "测试孩子是否能读出故事中的短句",
    materials: "同69A",
    method: `在实施69A项时注意孩子是否能读出一个完整的句子。`,
    is_observation: true,
    order_in_domain: 17,
  },
  {
    domain_code: "verbal_cognition",
    item_code: "69C",
    name: "不出多处错误地阅读故事",
    goal: "测试孩子是否能不出多处错误地阅读故事",
    materials: "同69A",
    method: `在实施69A项时，注意孩子是否有许多错误。`,
    is_observation: true,
    order_in_domain: 18,
  },
  {
    domain_code: "cognition_performance",
    item_code: "6C",
    name: "与手偶从事复杂的游戏互动",
    goal: "测试孩子是否能用手偶与测试者互动表演情节",
    materials: "同6B",
    method: `拿一个手偶给孩子，另一个套在你的手上，说：'我们玩什么?'鼓励孩子和你一起使用2个手偶作为主要角色来演出一个小情节。`,
    order_in_domain: 1,
  },
  {
    domain_code: "cognition_performance",
    item_code: "6D",
    name: "指认手偶狗躯体的各部位",
    goal: "测试孩子是否能指认手偶狗躯体各部位",
    materials: "一只手偶狗",
    method: `把手偶狗套在你的手上，举在孩子可能够得到的地方，要他指认狗的a)眼睛 b)鼻子 c)耳朵 d)嘴等。`,
    order_in_domain: 2,
  },
  {
    domain_code: "cognition_performance",
    item_code: "7",
    name: "指认自己躯体的各部位",
    goal: "测试孩子是否能指认自己躯体各部位",
    method: `不要用任何手势，让孩子指出他自己的a)眼睛 b)鼻子 c)耳朵 d)嘴巴。`,
    order_in_domain: 3,
  },
  {
    domain_code: "cognition_performance",
    item_code: "8C",
    name: "接受性辨认三种几何形状",
    goal: "测试孩子是否能接受性辨认三种几何形状",
    materials: "同8A",
    method: `把三个拼图块放在桌子上告诉孩子：'给我圆形'。对正方形、三角形要重复同样的实施步骤。`,
    order_in_domain: 4,
  },
  {
    domain_code: "cognition_performance",
    item_code: "11C",
    name: "大小概念(接受性辨认大小)",
    goal: "测试孩子是否能接受性辨认大小概念",
    materials: "同11A",
    method: `把一大一小的两个拼块放在桌子上。把小块放在孩子左边，大块放在孩子右边，对他说'把小块给我'。然后说'把大块给我'。`,
    order_in_domain: 5,
  },
  {
    domain_code: "cognition_performance",
    item_code: "12",
    name: "完成四块式小猫图形联锁式拼图",
    goal: "测试孩子是否能完成小猫联锁式拼图",
    materials: "四块式小猫图形联锁式拼图板",
    method: `把拼图块放在桌子上向孩子说明要把拼图块拼到一起('把它们拼起来')。如果一段时间之后孩子仍难于理解或完成这项任务，则用四个拼块示范给他看。`,
    order_in_domain: 6,
  },
  {
    domain_code: "cognition_performance",
    item_code: "13",
    name: "完成六块式奶牛图形拼图",
    goal: "测试孩子是否能完成六块式奶牛拼图",
    materials: "六块式奶牛图形拼图板",
    method: `把六块式拼图板放在孩子前面的桌子上并对他说'这是一头奶牛。'然后向孩子说明把拼图板拼起来。`,
    order_in_domain: 7,
  },
  {
    domain_code: "cognition_performance",
    item_code: "14C",
    name: "接受性辨认5种颜色",
    goal: "测试孩子是否能接受性辨认5种颜色",
    materials: "同14A",
    method: `把5个碟子全部放在桌子上摆在孩子前面对他说：'把红色的给我。'对其余的碟子重复同样的实施步骤。`,
    order_in_domain: 8,
  },
  {
    domain_code: "cognition_performance",
    item_code: "38C",
    name: "接受性辨认9个汉字",
    goal: "测试孩子是否能接受性辨认9个汉字",
    materials: "同38A",
    method: `把9个汉字卡放在桌上。任意选择一个字，让孩子把字卡递给你。`,
    order_in_domain: 9,
  },
  {
    domain_code: "cognition_performance",
    item_code: "41",
    name: "写出自己的名字",
    goal: "测试孩子是否能写出自己的名字",
    materials: "同38A",
    method: `翻开小册子中空白一页放在孩子面前。告诉他'写你的名字'。`,
    order_in_domain: 10,
  },
  {
    domain_code: "cognition_performance",
    item_code: "43",
    name: "在小袋内通过触摸辨认5种物品",
    goal: "测试孩子是否能通过触摸辨认袋内5种物品",
    materials: "一只小口袋，内有一支铅笔，一块积木，一支蜡笔，一只球以及一枚硬币",
    method: `把装有物品的袋子放在孩子面前的桌子上。不让孩子往袋子里看，要他把手伸进袋子，告诉他把你所要求的每一件物品拿出来。`,
    order_in_domain: 11,
  },
  {
    domain_code: "cognition_performance",
    item_code: "44",
    name: "用毡块贴出男孩图象",
    goal: "测试孩子是否能用毡块贴出男孩图象",
    materials: "一块毡板，九块毡片(脸，带胳膊的躯体，两条腿，头发，眼睛，鼻子和嘴)",
    method: `把毡板和毡块放在孩子面前的桌子上。用其中一块作示范，告诉孩子怎样往毡板上贴毡片。`,
    order_in_domain: 12,
  },
  {
    domain_code: "cognition_performance",
    item_code: "49D",
    name: "接受性地辨认2到6块积木",
    goal: "测试孩子是否能接受性辨认2到6块积木",
    materials: "同49C",
    method: `至少把8块积木放在孩子面前。要他给你两块积木。然后要孩子递给你6块积木。`,
    order_in_domain: 13,
  },
  {
    domain_code: "cognition_performance",
    item_code: "50",
    name: "执行两步指令",
    goal: "测试孩子是否能执行两步指令",
    materials: "杯子一只，积木一块",
    method: `把一些积木放在桌子上，边上再放一只杯子。对他说：'把一块积木放进杯子，再把杯子放在地板上。'`,
    order_in_domain: 14,
  },
  {
    domain_code: "cognition_performance",
    item_code: "58",
    name: "找到藏在杯子下的糖果",
    goal: "测试孩子是否能找到藏在杯子下的糖果",
    materials: "3只杯子和一些糖果",
    method: `在桌子上把3只杯子摆成一排，并引起孩子的注意。把一块糖果放在中间杯子下，缓慢地把中间的杯子与你右手的杯子变换位置，向孩子说明去找到糖果。`,
    is_observation: true,
    order_in_domain: 15,
  },
  {
    domain_code: "cognition_performance",
    item_code: "59",
    name: "用手势表达5种物品的用途",
    goal: "测试孩子是否能用手势表达5种物品用途",
    materials: "5张功能卡片，分别带有下列图画：哨子、球、鼓、钥匙和锯",
    method: `随意选出一张卡片给孩子看，向他说明要用手势去表达如何使用它('做给我看，你用它做什么')。`,
    is_observation: true,
    order_in_domain: 16,
  },
  {
    domain_code: "cognition_performance",
    item_code: "61A",
    name: "依据颜色或形状把12张卡片分类成组",
    goal: "测试孩子是否能依据颜色或形状把卡片分类成组",
    materials: "分类卡片I，共12张，由4种形状(菱形、圆形、正方形和三角形)及3种颜色(绿、红、紫色)组成",
    method: `把12张卡片随意堆放在孩子面前的桌子上。向他说明去把它们分成组。`,
    order_in_domain: 17,
  },
  {
    domain_code: "cognition_performance",
    item_code: "61B",
    name: "预想常规的做法",
    goal: "观察孩子是否能理解测试常规做法",
    materials: "盛测试器材用的塑料筐",
    method: `在测试过程中，每当一项任务完成时，就把该项所用过的器材归入塑料筐中。鼓励孩子来帮助这样做。`,
    is_observation: true,
    order_in_domain: 18,
  },
  {
    domain_code: "cognition_performance",
    item_code: "62B",
    name: "接受性地辨认语言读本中的图片",
    goal: "测试孩子是否能接受性辨认语言读本图片",
    materials: "同62A",
    method: `把语言读本放在孩子面前，图片要对着他。翻到第一页，并引起他的注意。然后问他'哪个是杯子?'，'杯子在哪?'等。`,
    order_in_domain: 19,
  },
  {
    domain_code: "cognition_performance",
    item_code: "68",
    name: "对口头指令做出反应",
    goal: "测试孩子是否能对口头指令做出反应",
    materials: "一只小球，一只杯子，一只玩偶狗，一个装得下一只杯子的盒子",
    method: `把这些物品放在孩子面前的桌子上，并引起孩子的注意。然后说出下列指令：1)敲打盒子 2)拍拍小狗 3)站起来跳下 4)把杯子放到盒子里，然后坐下 5)敲敲门，再摸摸墙。`,
    order_in_domain: 20,
  },
  {
    domain_code: "sensation",
    item_code: "2",
    name: "不适当地察看三个触摸块",
    goal: "观察孩子对触摸块的感觉反应是否适当",
    materials: "三个触摸块(毛的、糙面的、刻有凹槽的)",
    method: `把三个木块放在孩子面前，向孩子说明去察看这些木块，然后注意孩子对木块的反应。`,
    order_in_domain: 1,
  },
  {
    domain_code: "sensation",
    item_code: "3B",
    name: "无利眼",
    goal: "观察孩子是否展示出利眼",
    materials: "同3A",
    method: `在进行项目3A(操作万花筒)时，注意孩子是否明显地展示出利眼。如果孩子用一只眼睛靠近万花筒，然后换另一只眼睛，就重复这项任务。`,
    is_observation: true,
    order_in_domain: 2,
  },
  {
    domain_code: "sensation",
    item_code: "10",
    name: "跨过中线去取得拼图块",
    goal: "观察孩子是否能跨过中线取得拼图块",
    materials: "四块式(雨伞、小鸡、蝴蝶、梨)拼图板",
    method: `把拼图块从拼图板上拿下来，但把模板留在孩子面前。把雨伞、小鸡放在孩子左手方向靠近模板的地方，把蝴蝶、梨放在孩子右手方向，向孩子说明再次把拼图块放到拼图板上。`,
    order_in_domain: 3,
  },
  {
    domain_code: "sensation",
    item_code: "16",
    name: "听见并寻找响板声音的方位",
    goal: "测试孩子听见响板声后的反应及方向辨认",
    materials: "响板",
    method: `当孩子从事另一项任务时把响板放在孩子看不到的地方然后响亮地发出啪啪声，注意孩子的反应。`,
    order_in_domain: 4,
  },
  {
    domain_code: "sensation",
    item_code: "18",
    name: "无利脚",
    goal: "观察孩子是否展示出利脚",
    materials: "同17A",
    method: `在实施项目17C(踢球)过程中，注意孩子是否一贯地使用同一只脚。`,
    is_observation: true,
    order_in_domain: 5,
  },
  {
    domain_code: "sensation",
    item_code: "29",
    name: "听见并寻找哨声方位",
    goal: "测试孩子听见哨声后的反应及方向辨认",
    materials: "一只哨子",
    method: `当孩子从事另外一项活动时，把哨子藏在手里，然后大声地吹，并注意孩子的反应。`,
    order_in_domain: 6,
  },
  {
    domain_code: "sensation",
    item_code: "42",
    name: "无利手",
    goal: "观察孩子是否展示出利手",
    method: `在实施31-41项目时注意孩子是否明晰地显示出利手。`,
    is_observation: true,
    order_in_domain: 7,
  },
  {
    domain_code: "sensation",
    item_code: "60",
    name: "听见并寻找手摇铃声音的方位",
    goal: "测试孩子听见手摇铃声后的反应及方向辨认",
    materials: "一个手摇铃",
    method: `当孩子从事另一项活动时，藏起手摇铃。然后用力摇动，并注意孩子的反应。`,
    order_in_domain: 8,
  },
  {
    domain_code: "emotion",
    item_code: "25",
    name: "对身体接触作出不适当反应",
    goal: "观察孩子对身体接触的反应是否适当",
    method: `向孩子说明你要把他抱起来，然后举起他缓缓地转圈。如果他太重了，就拉着他的手一起转圈。`,
    order_in_domain: 1,
  },
  {
    domain_code: "emotion",
    item_code: "26",
    name: "对镜子映象作出不适当反应",
    goal: "观察孩子对镜子映象的反应是否适当",
    materials: "墙面镜或手镜",
    method: `把孩子带到镜子前。向他说明去看他的映象('你看到了谁?')，注意孩子的反应。`,
    order_in_domain: 2,
  },
  {
    domain_code: "emotion",
    item_code: "27",
    name: "对被挠痒痒作出不适当反应",
    goal: "观察孩子对被挠痒痒的反应是否适当",
    method: `开玩笑地对孩子挠痒痒，注意他的反应。`,
    order_in_domain: 3,
  },
  {
    domain_code: "social_interaction",
    item_code: "25",
    name: "对身体接触作出不适当反应",
    goal: "观察孩子对身体接触的反应是否适当",
    method: `向孩子说明你要把他抱起来，然后举起他缓缓地转圈。如果他太重了，就拉着他的手一起转圈。`,
    order_in_domain: 1,
  },
  {
    domain_code: "social_interaction",
    item_code: "47",
    name: "不能与测试者进行互动",
    goal: "观察孩子是否能与测试者进行互动",
    method: `在非结构化游戏过程中注意孩子是否想引起你的注意。`,
    is_observation: true,
    order_in_domain: 2,
  },
  {
    domain_code: "social_interaction",
    item_code: "48",
    name: "对测试者声音作不适当的反应",
    goal: "观察孩子对测试者声音的反应是否适当",
    method: `在非结构化游戏阶段结尾时实施此项目。当孩子不看着你也不全神贯注于任何活动时，喊他的名字，让他回到座位上。`,
    is_observation: true,
    order_in_domain: 3,
  },
  {
    domain_code: "play_interest",
    item_code: "46",
    name: "不适当地独自游戏",
    goal: "观察孩子独自游戏的方式是否适当",
    method: `非结构化游戏阶段：向孩子说明除了那些还未使用过的测试物品以外，他可以独自玩他想要玩的任何东西。你坐在桌子旁，至少在两分钟之内不要与孩子讲话或同他一起玩。`,
    is_observation: true,
    order_in_domain: 1,
  },
  {
    domain_code: "play_interest",
    item_code: "54A",
    name: "对绳子作出不适当反应",
    goal: "观察孩子对绳子的反应是否适当",
    materials: "一盒大珠子，一条末端打了结的粗线绳",
    method: `先把绳子放在孩子面前的桌子上。然后你开始从盒子里慢慢拿出珠子，放到你的衣兜里。注意孩子如何对绳子作出反应。`,
    order_in_domain: 2,
  },
];

/** 发展能力（功能领域）评分等级: 通过 / 中间反应 / 通不过 */
export const CARS_FUNCTION_LEVELS = [
  { value: "P", label: "通过", desc: "能独立完成任务" },
  { value: "M", label: "中间反应", desc: "未能完成但有意识/在协助下尝试" },
  { value: "F", label: "通不过", desc: "不能完成且不知如何做" },
] as const;

/** 病理学特征评分等级: 没有 / 轻度 / 重度 */
export const CARS_PATHOLOGY_LEVELS = [
  { value: "N", label: "没有", desc: "反应适当，符合年龄" },
  { value: "L", label: "轻度", desc: "反应稍有不适当" },
  { value: "S", label: "重度", desc: "反应非常不适当" },
] as const;

/** 仿画评分标准(适用于项目32-36) */
export const CARS_DRAWING_CRITERIA: Array<{
  item_code: string;
  name: string;
  pass_standard: string;
  mid_standard: string;
  fail_standard: string;
  note: string;
}> = [
  {
    item_code: "32",
    name: "垂直线 (项目32)",
    pass_standard: `3次试画中不需示范至少一次画出垂直线，且和样本长度接近`,
    mid_standard: `设法画垂直线但画的线弯曲，或不象垂直线而象水平线，或与样本长度差异大；需要示范才尝试`,
    fail_standard: ``,
    note: "不能或不试图画垂直线（如乱涂，拿着蜡笔接近纸张但并不画）",
  },
  {
    item_code: "33",
    name: "圆形 (项目33)",
    pass_standard: `3次试画中不需示范至少一次画出闭合圆，无大缺口或棱角`,
    mid_standard: `设法画圆形但圆有很大缺口或棱角；只是作连续的圆形涂划；需要示范才尝试`,
    fail_standard: ``,
    note: "不能或不试图画圆（画的图形一点也不象圆）",
  },
  {
    item_code: "34",
    name: "正方形 (项目34)",
    pass_standard: `3次试画中至少一次画出闭合正方形，四边近似等长，四角基本90°，线条允许稍波动`,
    mid_standard: `设法画正方形但不是闭合图形，四边不等长或角不接近90°；四边明显呈波浪形；需要示范才尝试`,
    fail_standard: ``,
    note: "不能或不试着画正方形（画的图形一点也不象正方形）",
  },
  {
    item_code: "35",
    name: "三角形 (项目35)",
    pass_standard: `3次试画中不需示范至少一次画出闭合三角形，三边近似相等，三个角颇具角形；允许稍呈波浪状；等腰或直角三角形也可`,
    mid_standard: `设法画出三角形但不是闭合图形，三边长度不相等，三个角不成形；三边明显呈波浪形；需要示范才尝试`,
    fail_standard: ``,
    note: "不能或不试着画三角形（画的图形一点也不象三角形）",
  },
  {
    item_code: "36",
    name: "菱形 (项目36)",
    pass_standard: `3次试画中不需示范至少一次画出闭合菱形，四边长度相近，四条线相当直`,
    mid_standard: `设法画出菱形但不是闭合图形，四边长度不相近，线条明显呈波浪状；需要示范才尝试`,
    fail_standard: ``,
    note: "不能或不试着画菱形（画的图形一点也不象菱形）",
  },
];

/** 根据领域 code 判断是否为病理学领域 */
export function isPathologyDomain(domainCode: string): boolean {
  return CARS_DOMAINS.find((d) => d.code === domainCode)?.is_pathology ?? false;
}

/** 根据领域 code 获取评分等级 */
export function getScoreLevelsForDomain(domainCode: string) {
  return isPathologyDomain(domainCode)
    ? CARS_PATHOLOGY_LEVELS
    : CARS_FUNCTION_LEVELS;
}
